CREATE TABLE `todolist` (
	`id` BIGINT(19) NOT NULL AUTO_INCREMENT,
	`Name` VARCHAR(80) NOT NULL ,
	`Description` VARCHAR(100)NOT NULL ,
	`Status` VARCHAR(100) NOT NULL,
	PRIMARY KEY (`id`) USING BTREE
)